### ISSUE TITLE
Not working with Laravel API

### ISSUE THREAD

**Issue by doftwerks-west-african** [antonioribeiro/google2fa#165]
I was able to get it to work on the web, but implementing it with Laravel API throws an error. I will like to know if I can override the verification process to allow for API verification. Thnaks

**Comment by bengearig** [comment]
@doftwerks-west-african I am using it successfully in my Laravel API application. You may need to further investigate your implementation for errors.

If you are using the [google2fa-laravel](https://github.com/antonioribeiro/google2fa-laravel) library, then you may wish to check there for info. If you are using that library and you have verified that your implementation is correct, then it would be more appropriate to create the issue there instead of here.
