### ISSUE TITLE
Typo in a code of the Google2FA class on line 397 (8.x - php 7.4)

### ISSUE THREAD

**Issue by mozg3000** [antonioribeiro/google2fa#192]
A comma at this line of a code crashes php script
https://github.com/antonioribeiro/google2fa/blob/98c9e0544c9467b427c323a54a193a8f3b5762ec/src/Google2FA.php#L396

because it is not allowed for php version < 8

**Comment by spaze** [comment]
Thanks for the bug, after reading the report I've realized that the tests aren't actually using the selected PHP version and are always executed with the latest PHP version so the code with the trailing comma was never executed on PHP 7.x.

And the trailing comma was also introduced by me in #187, sorry.

The fix for both is in #196, hopefully it will be merged and released soon.

**Comment by spaze** [comment]
Fixed in #211
