### ISSUE TITLE
Backup Code

### ISSUE THREAD

**Issue by plazari15** [antonioribeiro/google2fa#85]
Have an way to create a Backup list of codes, like if my user don't have the cellphone next, he/her can use one code of the list.

**Comment by antonioribeiro** [comment]
Not exactly the purpose of google2fa, maybe the case for a framework-specific package like [google2fa-laravel](https://github.com/antonioribeiro/google2fa-laravel).

But I just published a [Backup/Recovery](https://github.com/antonioribeiro/recovery) package, so it can help people, at least, generate the codes.

**Comment by tonybyng** [comment]
Hi. Thanks for a great package.  I had a similar question but have just had a look at the backup/recovery package. Am I right in thinking that we use the recovery package to generate a set of codes when a user is logged in, store them against the users account and modify the validate process to accept one of the generated codes instead of the 6 digit authenticator code?

**Comment by antonioribeiro** [comment]
Yes, exactly, but 

"generate a set of codes when a user register him/herself" 

and not

"generate a set of codes when a user is logged in"

And I would also give a way for the user to regenerate them.
