### ISSUE TITLE
External Service for QR-Code that includes the secret code

### ISSUE THREAD

**Issue by apreiml** [antonioribeiro/google2fa#86]
Hello,

regarding `QRCode::getQRCodeGoogleUrl`. I don't think it is a good idea to use an external service for showing the qr code containing the secret key. Shouldn't this secret key be only in the hands of the one to be authenticated? If you use this method, also an external service gets this secret information.

A major security flaw imho.

Kind Regards

**Comment by tankerkiller125** [comment]
There is an option for people who don't want to send it to google, simply put though some servers people use are very ill equipped to generate and show QR codes (generally cheap shared hosting) and because of this they need the option to have google or another provider generate the code for them.

**Comment by antonioribeiro** [comment]
@apreiml, people should know it's better inline their QRCode themselves via bacon-qr-code or anything else, but you are right, to not inform this is security issue, so I just changed the way it works: user (developer) has now to authorise it by 

```php
$google2fa->setAllowInsecureCallToGoogleApis(true);
```

Before

```php
$google2fa->getQRCodeGoogleUrl(
    'YourCompany',
    $user->email,
    $user->google2fa_secret
);
```

Otherwise it will throw an exception with the following message:

```
It's not secure to send secret keys to Google Apis, you have to explicitly allow it by calling $google2fa->setAllowInsecureCallToGoogleApis(true).
```

Tagged v3.0.0, since this is a huge breaking change.

Thanks for reporting it.

**Comment by vdomah** [comment]
Hi!
Why can't I find methods getQRCodeGoogleUrl and setAllowInsecureCallToGoogleApis in the sources? I'm getting errors about absence if this methods and I indeed can't find them in this package
Thanks in advance!
